spring.application.name=OnlineStore2

spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=gdyds5G71gh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

stripe.secret.key = ${STRIPE_API_KEY}

spring.ai.openai.base-url=http://localhost:12434/engines
spring.ai.openai.api-key=unused
spring.ai.openai.chat.options.model=docker.io/ai/llama3.2:latest

# Disable unused OpenAI auto-configurations
spring.ai.openai.audio.speech.enabled=false
spring.ai.openai.audio.transcription.enabled=false
spring.ai.openai.image.enabled=false
spring.ai.openai.embedding.enabled=false